# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbac17d38878cda232e2d9ee30f6292802121e0fdd61e4391bf7bf5dadcca8f73b0ce8b66826c31ac124f44c25693e6c63476644c2052087f8456a9986248e53

test:
  secret_key_base: 78513ddeb6851e90f0792f735141bbf133047f283ec7ff31a9e7c2d62ddb1d1c92f843b820a0e8668582f2c76b461ad32c6aa0b978f18ac606a04d0a61b870cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
